include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated
    - lib/l10n/l10n.dart
linter:
  rules:
    public_member_api_docs: false
