targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
    builders:
      mockito|mockBuilder:
        enabled: true
        generate_for:
          - test/test_mocks/test_repository_mocks.dart
      json_serializable|json_serializable:
        generate_for:
          - lib/shared/models/**.dart
      freezed|freezed:
        generate_for:
          - lib/shared/models/**.dart
          - lib/components/*/bloc/**.dart
          - lib/shared/bloc/**.dart
      injectable_generator|injectable_builder:
        generate_for:
          - lib/components/*/bloc/**.dart
          - lib/shared/bloc/**.dart
          - lib/shared/data_provider/**.dart
          - lib/shared/helpers/get_it_service_locator.dart
          - lib/shared/repositories/**.dart
