part of '../widget_keys.dart';

class _WidgetKeys {
  /// COMMENT: Add new variable here when you add a new file for widget keys
  final nawbar = _NawbarKeys();
  final question = _QuestionKeys();
  // final filter = _FilterKeys();
  final messageField = _MessageFieldKeys();
  final footer = _FooterKeys();
  final dropListField = _DropListFieldKeys();
  final storyCard = _StoryCardKeys();
  final box = _BoxKeys();
  final cardTextDetail = _CardTextDetailKeys();
  final workCard = _WorkCardKeys();
  final cardTextDetailEvaluate = _CardTextDetailEvaluateKeys();
  final cardAddImage = _CardAddImageKeys();
  final newsCard = _NewsCardKeys();
  final discountCard = _DiscountCardKeys();
  final switchKeys = _SwitchKeys();
  // final buttonMob = _ButtonMobKeys();
  final dropChip = _DropChipKeys();
  final chip = _ChipKeys();
  final filterPopupMenu = _FilterPopupMenuKeys();
  final pagination = _PaginationKeys();
  final languageSwitcher = _LanguageSwitcherKeys();
  final checkPoint = _CheckPointKeys();
  final scaffold = _ScaffoldKeys();
  final profileCard = _ProfileCardKeys();
  final donateCard = _DoanteCardKeys();
  final emailPasswordFields = _EmailPasswordFieldsKeys();
  final leftCard = _LeftCardKeys();
  final signUpBottomButtons = _SignUpBottomButtonsKeys();
  final rate = _RateKeys();
  final chatInput = _ChatInputKeys();
  final checkPointSingle = _CheckPointSingleKeys();
  final workRequestCard = _WorkRequestCardKeys();
  final dialogs = _DialogsKeys();
  final filterChip = _FilterChipKeys();
  final buttonAdditional = _ButtonAdditionalKeys();
  final statisticBox = _StatisticBoxKeys();
  final reportDialog = _ReportDialogKeys();
  final notificationLink = _NotificationLinkKeys();
  final cityList = _CityListKeys();
  final menuDialog = _MenuDialogKeys();
  final mobNavigation = _MobNavigationKeys();
  final mobFeedback = _MobFeedbackKeys();
  final emailButton = _EmailButtonsKeys();
  final userEmailDialog = _UserEmailDialogKeys();
  final buttonBottomLine = _ButtonBottomLineKeys();
  final donateButton = _DonateButtonKeys();
  final doubleButton = _DoubleButtonKeys();
  final loadingButton = _LoadingButtonKeys();
  final mobUpdate = _MobUpdateKeys();
  final networkBanner = _NetworkBannerKeys();
  final cardEmpty = _CardEmptyKeys();
}
