// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEyjiJOQxksq81cI865BN4T28i-P1gGGo',
    appId: '1:32851885972:web:cfc67afc73c0e1cbecd981',
    messagingSenderId: '32851885972',
    projectId: 'veteran-development',
    authDomain: 'veteran-development.firebaseapp.com',
    storageBucket: 'veteran-development.appspot.com',
    measurementId: 'G-PEH6XXFC05',
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyA8CbivBU82h3WhxgoZ0mkdMq5y1OEfbQk',
  //   appId: '1:32851885972:android:8c88121886d3834eecd981',
  //   messagingSenderId: '32851885972',
  //   projectId: 'veteran-development',
  //   storageBucket: 'veteran-development.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCbrgwKWeMZ69SHecID9NFHohsA7v8YOss',
  //   appId: '1:32851885972:ios:87468196658b11a8ecd981',
  //   messagingSenderId: '32851885972',
  //   projectId: 'veteran-development',
  //   storageBucket: 'veteran-development.appspot.com',
  //   iosClientId:
  //       '32851885972-qe9sf5udiu1sn1il656tpl2ifvdlgtcr.apps.googleusercontent.com',
  //   iosBundleId: 'ua.com.kozatskarada.kozak',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCbrgwKWeMZ69SHecID9NFHohsA7v8YOss',
  //   appId: '1:32851885972:ios:541a9f206a1c8d7fecd981',
  //   messagingSenderId: '32851885972',
  //   projectId: 'veteran-development',
  //   storageBucket: 'veteran-development.appspot.com',
  //   iosClientId:
  //       '32851885972-dug7bniacnr414ninjv0uc45v527q1j7.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.myApp',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyBEyjiJOQxksq81cI865BN4T28i-P1gGGo',
  //   appId: '1:32851885972:web:3bb208f45cb967d1ecd981',
  //   messagingSenderId: '32851885972',
  //   projectId: 'veteran-development',
  //   authDomain: 'veteran-development.firebaseapp.com',
  //   storageBucket: 'veteran-development.appspot.com',
  //   measurementId: 'G-DKS1DNPQVC',
  // );
}
