name: DEVELOPMENT Cloudflare Deployments Cleaner

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [main]
concurrency:
  group: dev-—Åloudflare-cleaner-$
  cancel-in-progress: true

jobs:
  web_build:
    uses: CodingHouseStudio/flutter_workflows/.github/workflows/cloudflare_deployments_cleaner.yml@main
    with:
      project_name: "veteran-development"
