name: Integration Test
# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [main]
concurrency:
  group: exp-prod-$
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    # defaults:
    #   run:
    #     working-directory: ${{inputs.working_directory}}

    # runs-on: ${{inputs.runs_on}}

    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: ${{ inputs.flutter_channel }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Integration Tests
        run: flutter test --platform all --test-tags integration
