name: Integration Tests
# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [main]
concurrency:
  group: int-test-$
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    uses: CodingHouseStudio/flutter_workflows/.github/workflows/integration_test.yml@main
    secrets: inherit
    with:
      flutter_channel: stable
      flutter_version: 3.27.1
      # format_directories: "lib test"
