name: Mobile Integration Tests
# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [main]
concurrency:
  group: int-android-test-$
  cancel-in-progress: true

jobs:
  build:
    uses: CodingHouseStudio/flutter_workflows/.github/workflows/android_integration_test.yml@main
    secrets: inherit
    with:
      FLAVOUR: "production"
