name: Mobile Integration Tests
# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [main]
concurrency:
  group: int-android-test-$
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    uses: CodingHouseStudio/flutter_workflows/.github/workflows/android_integration_test.yml@main
    secrets: inherit
    with:
      FLAVOUR: "development"
      TEST_TARGETS: "discounts"
